### ISSUE TITLE
First version

### ISSUE THREAD

**Issue by screw123** [bsol-oss/react-datatable2#1]
First version is expected to have at least following:
1. React-table
2. Look and feel of Chakra UI table should follow Chakra Pro https://pro.chakra-ui.com/components/application/tables.
Source code below:
[TableWithSearch.zip](https://github.com/bsol-oss/react-datatable2/files/11689698/TableWithSearch.zip)
3. Using i18next on all table headers and labels:
![image](https://github.com/bsol-oss/react-datatable2/assets/18388411/db1179a9-c94b-4772-9bba-7619204912ef)
4. Accept a prop `apiUrl`, if it's missing show an error message saying "apiUrl is missing or malformed".  If it's available and is valid load data from the URL using GET request and then display.
5. API response you can have a sample from the demo server I provided to you earlier http://5.78.97.128:8081/api/g/subarea/all.  This is also the sample API you can use against for development.
6. You should also expect a prop "columns" to be provided, sample you can check from old version's Storybook https://github.com/bsol-oss/react-datatable/tree/main/src/components/DataTableSever/stories
7. The major change against old version, is we want the component to be easily composable, instead of 1 big components with tons of props.  What it means is we want individual components to be exported, so it can be used like this:

```
import {DataTable, Controls, SearchBar, DisplayModeButtons, TableHeaders, TableData, DataLoadingSkeleton, Footer, PaginationControl, DataStats} from '@bsol-oss/react-datatable2'

<DataTable>
  <Controls>
    <SearchBar />
    <DisplayModeButtons enabledView={['ROW', 'ROWCONDENSED']} />
  </Controls>
  <TableHeaders columns={columns} />
  <TableData
    apiUrl="xxx"
    onLoad={DataLoadingSkeleton}
  />
  <Footer>
    <PaginationControl />
    <DataStats />
  </Footer>
</DataTable>
```
Note: Above is JUST AN EXAMPLE.  But it highlights we want to revamp the component to be Chakra UI style composable and flexible for all the different use cases.

You should refer to "DataTableServer" https://github.com/bsol-oss/react-datatable/tree/main/src/components/DataTableSever, not "DataTable"

**Comment by screw123** [comment]
Hi @Risk-taker0501 please refer to above for a summary of the first version we are looking for.  I estimate it may take a few days to absorb and re-write into the above mode.  I recommend re-write to avoid bringing old issues to new code.

But the old code is having 95%+ features we wants and it's 70% there except being bulky.

In the next few days I will add other tasks to highlight the changes we need to put in after the first version,  thanks!

**Comment by Risk-taker0501** [comment]
Okay, I got it. I will follow your idea.
would you use Slack for our communication?
It will be better.

**Comment by Risk-taker0501** [comment]
I created Chakra DataTable that you sent me.
And divided 3 individual components(searchWrapper, MainTable, PageWapper) and use like this:
      <DataTable>
        <Box>
          <SearchWrapper />
          <MainTable />
          <PageWrapper />
        </Box>
      </DataTable>
 
![image](https://github.com/bsol-oss/react-datatable2/assets/129389058/dd1ed8c0-15e9-4511-aef9-a76523c672bf)
