### ISSUE TITLE
Task03: Global Search Bar should be usable for search

### ISSUE THREAD

**Issue by screw123** [bsol-oss/react-datatable2#12]
Using react-table, and refer to how we do it in old repo, update code for global search bar so it's functional.

**Comment by Risk-taker0501** [comment]
I'm going to React.useContext for global search of seperate table components.

**Comment by Risk-taker0501** [comment]
Of course. I'm waiting to merge last PR.
I will make new PR for search feature, in a few min.

**Comment by Risk-taker0501** [comment]
Sorry. I will remember to link PR to issues.

What is your whatsapp number?
This is my number: +1 631 458 4979
