### ISSUE TITLE
[Task 13] Need to enable individual column searching

### ISSUE THREAD

**Issue by screw123** [bsol-oss/react-datatable2#36]
Check out the old react-datatable repo: https://bsol-oss.github.io/react-datatable/?path=/story/data-table--with-cell-height-width-variations
![image](https://github.com/bsol-oss/react-datatable2/assets/18388411/63fe76f3-7cfb-4dc1-85a4-6c741c2ef929)
These are the search bar that will allow filtering just on an individual column.

Before start pls read again carefully the background I send over on Slack, and make sure you tried and understand how to work with the API (by checking out existing code how to form the querystring properly)

Again link to the old datatable repo https://github.com/bsol-oss/react-datatable

The search bar should mimic what the global search bar is doing:
1. let the user key in whatever
2. When search icon is clicked or pressed enter, trigger API call for the search

Any questions pls ask me in Slack.

**Comment by Muhammad-Umar-Khan** [comment]
@screw123 are we sure about the search on status?

**Comment by screw123** [comment]
Can search on some other fields, you don’t need to implement the control on
all fields.
