### ISSUE TITLE
[Task 15] a control for showing numer of records per page

### ISSUE THREAD

**Issue by screw123** [bsol-oss/react-datatable2#42]
![image](https://github.com/bsol-oss/react-datatable2/assets/18388411/267fef63-42f0-42ac-b301-823af7790657)
Need a component like this in footer

You can check out this example directly from react-table
https://tanstack.com/table/v8/docs/examples/react/pagination-controlled

**Comment by Muhammad-Umar-Khan** [comment]
@screw123 @jyotipadhi1 it's done now.
